name: Svelte_UI

on:
  workflow_call:
  push:
    branches:
      - develop # Develop branch contains both feature and bugfix commits when merged via PR
      - bugfix/*
      - hotfix/*
    paths:
      - 'svelte-ui/**'
      - '.github/workflows/svelte-ui.yml'

defaults:
  run:
    working-directory: svelte-ui

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4
      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # disable pnpm install for using pnpm cache
      
      # Step 3: Install Node.js and cache dependencies
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: svelte-ui/pnpm-lock.yaml
      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --shamefully-hoist
      # Step 5: Build
      - name: Build
        run: pnpm run build
      # Step 6: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: svelte_build_output
          # From all the files only these paths will be uploaded in directory named above
          path: |
            svelte-ui/build
            svelte-ui/package.json
            svelte-ui/node_modules
